import Mathlib

open Finset

variable {n : ℕ}

/-- Continuous piecewise linear functions on `ℝⁿ`, presented as the sublattice of
`ℝⁿ → ℝ` generated by the affine maps. -/
inductive CPWL : ((Fin n → ℝ) → ℝ) → Prop
  | affine (T : (Fin n → ℝ) →ᵃ[ℝ] ℝ) : CPWL ⇑T
  | sup {f g} (hf : CPWL f) (hg : CPWL g) : CPWL (f ⊔ g)
  | inf {f g} (hf : CPWL f) (hg : CPWL g) : CPWL (f ⊓ g)

/-- Wang and Sun index hinges by one less than the number of affine arguments, so an
`n`-order hinge on `ℝⁿ` takes `n + 1` of them. -/
def IsHinge (h : (Fin n → ℝ) → ℝ) : Prop :=
  ∃ (σ : ℝ) (L : Fin (n + 1) → ((Fin n → ℝ) →ᵃ[ℝ] ℝ)),
    (σ = 1 ∨ σ = -1) ∧
      h = fun x => σ * ((univ : Finset (Fin (n + 1))).sup' univ_nonempty fun i => L i x)

/-- A finite sum of `n`-order hinges. -/
def IsHH (f : (Fin n → ℝ) → ℝ) : Prop :=
  ∃ (K : ℕ) (h : Fin K → ((Fin n → ℝ) → ℝ)), (∀ k, IsHinge (h k)) ∧ f = ∑ k, h k
